server:
  port: 6060
spring:
  mvc:
  datasource:
    pathmatch:
      matching-strategy: ant_path_matcher
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quest-platform?serverTimezone=Asia/Shanghai
    username: root
    password: root


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.kh.qp.qp.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aliyun:
  sms:
    accessKeyID: LTAI5tLV9ip4TccZSQi8afne
    accessKeySecret: xgqN8vcqLDYAqn1rIMNdsXiREF1JuD
    signName: "合肥玥云"
    templateCode: 'SMS_219865010'


  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间
    timeout: 10000


